namespace Text_Adventure_Console_Game
{
    internal static class Treffen_mit_Morpheus
    {

        public static void Gespräch_mit_Morpheus()
        {
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Kapitel 3: Treffen mit Morpheus");
            Console.ReadKey();
            Console.Clear();
            Klasse_Jpeg_to_Asci_Generator.Morpheus_Treffen_ASCI();
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du fährst im Regen mit Trinity im Auto zu einem großem leerem Gebäude.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du gehst in den zweiten Stock und stehst vor einer großen Holztür.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du wirst hinein gebeten, drinnen erwartet dich Morpheus und heisst dich Willkommen.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Morpheus sagt: Setz dich Neo.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du fühlst dich im Moment sicher, wie Alice im Wunderland.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Während Sie in den Kaninchen Bau stürzt, hm?");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du sagst: Ja so ähnlich.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Morpheus: Ich kann es in deinen Augen lesen.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du siehst aus wie ein Mensch der das was er sieht hinnimmt.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Weil er damit rechnet das er wieder aufwacht.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Ironischerweise ist das nah an der Wahrheit.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Glaubst du dan das Schicksal, Neo?");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du sagst: Nein");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Morpheus: Warum nicht?");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du sagst: Mir misfällt der Gedanke mein Leben nicht unter Kontrolle zu haben.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Morpheus: ICH WEIß GANZ GENAU WAS DU MEINST!");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Ich will dir sagen wieso du hier bist");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du bist hier weil du etwas weißt, etwas das du nicht erklären kannst.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Aber du fühlst es,du fühlst es schon dein ganzes Leben lang.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Das mit der Welt etwas nicht stimmt, du weißt nicht was aber es ist da!");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Wie ein Splitter in deinem Kopf der dich verrückt macht.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Dieses Gefühl hat dich zu mir geführt.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Weisst du wovon ich Spreche?");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du sagst: Von der Matrix?");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Morpheus: Möchtest du wissen was genau sie ist?");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du nickst gespannt mit dem Kopf.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Morpheus: Die Matrix ist allgegenwertig, sie umgibt uns selbst hier ist sie in diesem Zimmer ");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du siehst sie wenn du aus dem Fenster guckst oder den Fernseher an machst.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du kannst sie spüren wenn du zur Arbeit gehst.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Oder in die Kirche.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Oder wenn du deine Steuern zahlst.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Es ist eine Scheinwelt, die man dir vorgauckelt um dich von der Wahrheit abzulenken.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du sagst: Welche Wahrheit?");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Morpheus: Das du ein Sklave bist Neo.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du wurdest wie alle in die Sklaverei geboren und lebst in einem Gefängnis das du weder anfassen, noch riechen kannst.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Ein Gefängnis, für deinen Verstand!");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Dummerweise, ist es schwer jemandem zu erklären was die Matrix ist.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Jeder muss sie selbst erleben!");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Morpheus öffnet ein silbernes Kästchen und entnimmt etwas.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Er beugt sich zu dir vor und spricht.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Dies ist deine letzte Chance, danach gibt es kein zurück!");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Schluckst du die blaue Kapsel, ist alles aus du wachst in deinem Bett auf und glaubst an das was du glauben willst.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Schluckst du die rote Kapsel, bleibst du im Wunderland.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Und ich führe dich in die tiefsten tiefen des Kaninchenbaus.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Du zögerst kurz und streckst dich dann zur roten Kapsel.");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Morpheus sagt: Bedenke! Alles was ich dir anbiete ist die Wahrheit, nicht mehr!");
            Console.ReadKey();
            Console.Clear();
            Console.SetCursorPosition(40, 0);
            Klasse_Jpeg_to_Asci_Generator.Kapsel_wählen_Bild();
            Console.SetCursorPosition(40, 12);
            Console.WriteLine("Wähle die blaue oder die rote Kapsel!");
            Console.SetCursorPosition(40, 13);
            Console.WriteLine("> ");
            Klasse_wähle_eine_Kapsel.Kapsel_Wählen_Rot_oder_Blau();
            Klasse_wähle_eine_Kapsel.Enter_The_Matrix();
            Console.Clear();
        }
    }
}